name: Domain Filter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:

env:
  MIHOMO_VERSION: 1.19.12  # Mihomo 版本

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # 允许推送文件到仓库
      pull-requests: write # 允许操作 Pull Request
      actions: write       # 允许删除 workflow 运行记录

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史以便提交

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests aiohttp  # 添加 aiohttp 依赖以支持异步下载

      - name: Run filter script
        run: |
          python filter.py
        continue-on-error: false  # 脚本失败时停止工作流


      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add OUTPUT/*/*
          if git diff --staged --quiet; then
            echo "没有文件变更，无需提交"
          else
            git commit -m "更新过滤后的域名文件和 MRS 文件 [自动生成]"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
